name: buzz-app
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1
  DEVELOPMENT_TEAM: 49V8Q5W76J
options:
  bundleIdPrefix: com.anthony-gufron
  deploymentTarget:
    MACOSX_DEPLOYMENT_TARGET: "15.0"
packages:
  RichTextKit:
    url: https://github.com/danielsaidi/RichTextKit
    from: 1.1.1
targets:
  buzz-app:
    type: application
    platform: macOS
    sources: [buzz-app]
    resources: [Resources]
    dependencies:
      - package: RichTextKit
    info:
      path: buzz-app/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UILaunchScreen: ""
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        LSApplicationCategoryType: public.app-category.productivity
        ATSApplicationFontsPath: .
        CFBundleDocumentTypes:
          - CFBundleTypeName: PDF Document
            CFBundleTypeRole: Viewer
            LSHandlerRank: Alternate
            LSItemContentTypes:
              - com.adobe.pdf
    settings:
      INFOPLIST_FILE: buzz-app/Info.plist
      ENABLE_TESTABILITY: YES

  buzz-appTests:
    type: bundle.unit-test
    platform: macOS
    sources: [buzz-appTests]
    buildSettings:
      ENABLE_TESTABILITY: YES
      DEFINES_MODULE: YES
    dependencies:
      - target: buzz-app
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.anthony-gufron.buzz-appTests
      ENABLE_TESTABILITY: YES
      base:
        INFOPLIST_FILE: buzz-app/Info.plist

  Polaread-Extension:
    type: app-extension
    platform: macOS
    sources: [Polaread-Extension]
    resources: [Resources]
    dependencies: []
    info:
      path: Polaread-Extension/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        NSExtension:
          NSExtensionPointIdentifier: com.apple.Safari.web-extension
          NSExtensionAttributes:
            WKAppBoundDomains: []
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.anthony-gufron.Polaread-Extension
      INFOPLIST_FILE: Polaread-Extension/Info.plist

schemes:
  buzz-app:
    build:
      targets:
        buzz-app: all
        buzz-appTests: all
        Polaread-Extension: all
    test:
      targets:
        - name: buzz-appTests
      gatherCoverageData: true
