name: Polaread
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1
  DEVELOPMENT_TEAM: 49V8Q5W76J
options:
  bundleIdPrefix: com.anthony-gufron
  deploymentTarget:
    MACOSX_DEPLOYMENT_TARGET: "15.0"
packages:
  RichTextKit:
    url: https://github.com/danielsaidi/RichTextKit
    from: 1.1.1
targets:
  Polaread:
    type: application
    platform: macOS
    sources: [Polaread]
    resources: [Resources]
    dependencies:
      - package: RichTextKit
    info:
      path: Polaread/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        LSApplicationCategoryType: public.app-category.productivity
        ATSApplicationFontsPath: .
        CFBundleDocumentTypes:
          - CFBundleTypeName: PDF Document
            CFBundleTypeRole: Viewer
            LSHandlerRank: Alternate
            LSItemContentTypes:
              - com.adobe.pdf
    settings:
      INFOPLIST_FILE: Polaread/Info.plist
      ENABLE_TESTABILITY: YES

  PolareadTests:
    type: bundle.unit-test
    platform: macOS
    sources: [PolareadTests]
    buildSettings:
      ENABLE_TESTABILITY: YES
      DEFINES_MODULE: YES
    dependencies:
      - target: Polaread
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.anthony-gufron.PolareadTests
      ENABLE_TESTABILITY: YES
      base:
        INFOPLIST_FILE: Polaread/Info.plist

schemes:
  Polaread:
    build:
      targets:
        Polaread: all
        PolareadTests: all
    run:
      target: Polaread
    test:
      targets:
        - name: PolareadTests
      gatherCoverageData: true
